# Generated by Django 2.2.7 on 2020-09-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=60)),
                ('tz', models.CharField(default='Europe/London', max_length=100)),
                ('activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.Period')),
            ],
        ),
    ]
